export type Role='ADMIN'|'SECRETARIA_SALUD'|'RESPONSABLE_INSTITUCIONAL'|'PROFESIONAL_SEGURIDAD';
export type CaseStatus='APLICACION_RECIBIDA'|'CLASIFICACION_REALIZADA'|'ALERTA_PENDIENTE_REVISION'|'VALORACION_SEGURIDAD_EN_CURSO'|'RUTA_ABIERTA'|'CONTACTO_INICIAL_REALIZADO'|'REMISION_REALIZADA'|'CONTACTO_RECEPTOR_CONFIRMADO'|'ATENCION_VALORACION_CONFIRMADA'|'SEGUIMIENTO_ACTIVO'|'CIERRE_PENDIENTE'|'CASO_CERRADO'|'EMERGENCIA_IDENTIFICADA'|'ACTIVACION_URGENTE_REALIZADA'|'TRANSFERENCIA_EN_CURSO'|'TRANSFERENCIA_CONFIRMADA';
export interface User{id:string;nombre:string;email:string;rol:Role;institucionId:string|null;activo:boolean;institucion?:{id:string;nombre:string}}
export interface Institution{id:string;nombre:string;codigo:string;tipo:string;direccion?:string|null;municipio:string;activa:boolean}
export interface Adolescent{id:string;codigo:string;edad:number}
export interface Alert{id:string;casoId:string;estado:'SIN_RESPONSABLE'|'PENDIENTE_VALORACION'|'EN_VALORACION'|'RESUELTA';responsableId:string|null;responsable?:Pick<User,'id'|'nombre'>|null;generadaAt:string;proximaAccion:string;caso?:Case}
export interface Application{id:string;institucionId:string;estado:'RECIBIDA_COMPLETA'|'RECIBIDA_INCOMPLETA';fechaEnvio:string;adolescente:Adolescent;resultado?:{perfilOperativo:string|null;safetyAlert:boolean;sintomasPuntaje?:number;sintomasBanda?:string};alerta?:Alert|null;institucion?:Institution;caso?:Case}
export interface Case{id:string;estado:CaseStatus;perfilOperativo:string|null;safetyAlertStatus:string|null;motivo:string;proximaAccion:string|null;fechaProximaAccion:string|null;fechaApertura:string;fechaCierre?:string|null;adolescente:Adolescent;institucion:Institution;responsableActual?:Pick<User,'id'|'nombre'|'rol'>|null;alerta?:Alert|null;aplicacion:{id:string;estado:string;versionInstrumento:string;fechaEnvio:string}}
export interface RouteAction{id:string;tipo:string;descripcion:string;estadoAnterior?:CaseStatus;estadoPosterior?:CaseStatus;createdAt:string;usuario?:Pick<User,'nombre'>}
export interface FollowUp{id:string;casoId:string;estado:'PROGRAMADO'|'REALIZADO'|'VENCIDO'|'CANCELADO';fechaProgramada:string;responsable:Pick<User,'id'|'nombre'>;caso?:Case;resultado?:string|null}
export interface DirectoryEntry{id:string;nombre:string;tipo:string;usoPrincipal:string;formaAcceso:string;telefono?:string|null;direccion?:string|null;horario?:string|null;territorio:string;activo:boolean;updatedAt:string}
export interface Referral{id:string;casoId:string;servicioId:string;institucionReceptora:string;profesionalReceptor?:string|null;observaciones?:string|null;fechaRemision:string;contactoRealizado:boolean;fechaContacto?:string|null;recepcionConfirmada:boolean;fechaConfirmacion?:string|null;servicio:Pick<DirectoryEntry,'id'|'nombre'|'tipo'|'territorio'|'activo'>;registradoPor:Pick<User,'id'|'nombre'|'rol'>}
export interface ProtectionRoute{id:string;casoId:string;tipoVulneracion:'VIOLENCIA_INTRAFAMILIAR'|'MALTRATO'|'ABUSO'|'EXPLOTACION'|'NEGLIGENCIA_GRAVE'|'OTRA_VULNERACION';descripcion:string;estado:'ACTIVA'|'CERRADA';fechaActivacion:string;fechaCierre?:string|null;motivoCierre?:string|null;activadaPor:Pick<User,'id'|'nombre'|'rol'>}
export interface AuditEntry{id:string;createdAt:string;accion:string;entidad:string;entidadId:string;usuario:Pick<User,'id'|'nombre'|'email'|'rol'>}
export interface Answer{pregunta:number;valor:number} export interface ApplicationInput{codigoAdolescente:string;edad:number;institucionId:string;lugarAplicacion:string;versionInstrumento:string;fechaInicio:string;respuestas:Answer[]}
export interface SafetyAssessmentInput{ideacionActual:boolean;intencion:boolean;plan:boolean;accesoMedios:boolean;intentoReciente:boolean;autolesionReciente:boolean;consumoRelevante:boolean;agitacion:boolean;desesperanza:boolean;adultoProtector:boolean;condicionesSeguridad:string;observaciones?:string|null}
export type DashboardResponse={metadata:{generadoAt:string;desde:string|null;hasta:string|null;institucionId:string|null;nominal:false};[key:string]:unknown};
